New log file opened at Fri Jul 03 11:46:16 PDT 2015 by 7116@Home
Taking next connection to: 53845
New client attempting to connect on port: 53847-53845
  Address = /192.168.0.101:53845
This client on port 53847 has uuid 736c4145-af4f-4511-b315-74d9f01f59c0 configName activator humanReadableName Activator protocolVersion 3 featureTags Vector()
Connected Clients: activator-736c4145-af4f-4511-b315-74d9f01f59c0
Taking next connection to: 53845
New client attempting to connect on port: 53848-53845
  Address = /192.168.0.101:53845
Handshake exception on socket: 53848
sbt.impl.ipc.HandshakeException: Unable to perform handshake
	at sbt.impl.ipc.Peer.handshake(IPC.scala:46)
	at sbt.impl.ipc.MultiClientServer.<init>(IPC.scala:150)
	at sbt.server.SbtServerSocketHandler$$anon$1.run(SbtServerSocketHandler.scala:43)
Caused by: java.net.SocketException: Software caused connection abort: recv failed
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
	at java.net.SocketInputStream.read(SocketInputStream.java:170)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:265)
	at java.io.DataInputStream.readInt(DataInputStream.java:387)
	at sbt.impl.ipc.Peer.receive(IPC.scala:95)
	at sbt.impl.ipc.Peer.handshake(IPC.scala:49)
	... 2 more
Taking next connection to: 53845
New client attempting to connect on port: 53849-53845
  Address = /192.168.0.101:53845
This client on port 53849 has uuid 24102425-3e80-46ec-b540-1424537fc604 configName activator humanReadableName Activator protocolVersion 3 featureTags Vector()
Connected Clients: activator-736c4145-af4f-4511-b315-74d9f01f59c0, activator-24102425-3e80-46ec-b540-1424537fc604
Taking next connection to: 53845
Checking to see if clients are empty...
We have 1 non-daemon clients, continuing serving connections.
Taking next connection to: 53845
